# Generated by Django 2.1.7 on 2019-03-28 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Denis Vorko', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('manual', models.TextField(blank=True, help_text='About this', max_length=1024)),
                ('image', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(default='Denis Vorko', help_text='author', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_denis_vorko.Author')),
            ],
        ),
    ]
