# Generated by Django 2.1.7 on 2019-03-28 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_denis_vorko', '0003_auto_20190328_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Denis Vorko', max_length=128)),
            ],
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-date_pub']},
        ),
        migrations.AlterField(
            model_name='job',
            name='author',
            field=models.ForeignKey(default='Denis Vorko', help_text='author', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='page_denis_vorko.Author'),
        ),
    ]
